Mesd\HelpWikiBundle\Entity\Comment:
    type:            entity
    table:           mesd_helpwiki_comment
    repositoryClass: Mesd\HelpWikiBundle\Entity\CommentRepository
    indexes:
        mesd_helpwiki_comment_page_id_idx:
            columns: [page_id]
        mesd_helpwiki_comment_user_id_idx:
            columns: [user_id]
    id:
        id:
            id:   true
            type: integer
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   mesd_helpwiki_comment_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        body:
            column:   body
            type:     text
            nullable: false
            unique:   false
        dateTime:
            column:   date_time
            type:     datetime
            nullable: false
            unique:   false
        status:
            column:   status
            type:     string
            length:   16
            nullable: false
            unique:   false
            options:
                comment: 'Available types: flagged, unapproved, approved'
        statusDateTime:
            column:   status_date_time
            type:     datetime
            nullable: false
            unique:   false
    manyToOne:
        user:
            targetEntity: Mesd\HelpWikiBundle\Model\UserSubjectInterface
            joinColumn:
                name:                 user_id
                referencedColumnName: id
        statusBy:
            targetEntity: Mesd\HelpWikiBundle\Model\UserSubjectInterface
            joinColumn:
                name:                 status_by_id
                referencedColumnName: id
        page:
            targetEntity: Page
            inversedBy:   comments
            joinColumn:
                name:                 page_id
                referencedColumnName: id