Mesd\HelpWikiBundle\Entity\History:
    type:            entity
    table:           mesd_helpwiki_history
    repositoryClass: Mesd\HelpWikiBundle\Entity\HistoryRepository
    indexes:
        mesd_helpwiki_history_page_id_idx:
            columns: [page_id]
        mesd_helpwiki_history_user_id_idx:
            columns: [user_id]
    id:
        id:
            id:   true
            type: integer
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   mesd_helpwiki_history_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        title:
            column:   title
            type:     string
            length:   255
            nullable: false
            unique:   false
        body:
            column:   body
            type:     text
            nullable: false
            unique:   false
        slug:
            column:   slug
            type:     string
            length:   255
            nullable: false
            unique:   false
        status:
            column:   status
            type:     string
            length:   16
            nullable: false
            unique:   false
            options:
                comment: 'Avaiable options: autosave, draft, unpublished, published, trashed'
        revision:
            column:   revision
            type:     integer
            nullable: false
            unique:   false
        dateTime:
            column:   date_time
            type:     datetime
            nullable: false
            unique:   false
    manyToOne:
        page:
            targetEntity: Mesd\HelpWikiBundle\Entity\Page
            inversedBy:   histories
            joinColumn:
                name:                 page_id
                referencedColumnName: id
                nullable:             false
        user:
            targetEntity: Mesd\HelpWikiBundle\Model\UserSubjectInterface
            joinColumn:
                name:                 user_id
                referencedColumnName: id
                nullable:             false