Mesd\HelpWikiBundle\Entity\Link:
    type:            entity
    table:           mesd_helpwiki_link
    repositoryClass: Mesd\HelpWikiBundle\Entity\LinkRepository
    indexes:
        mesd_helpwiki_link_page_id_idx:
            columns: [page_id]
    id:
        id:
            id:   true
            type: integer
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   mesd_helpwiki_link_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        routeAlias:
            column:   route_alias
            type:     string
            length:   255
            nullable: false
    uniqueConstraints:
        mesd_helpwiki_link_route_alias_unique_idx:
            columns: [route_alias]
    manyToOne:
        page:
            targetEntity: Mesd\HelpWikiBundle\Entity\Page
            inversedBy:   links
            joinColumn:
                name:                 page_id
                referencedColumnName: id
                nullable:             false