Mesd\HelpWikiBundle\Entity\Page:
    type:            entity
    table:           mesd_helpwiki_page
    repositoryClass: Mesd\HelpWikiBundle\Entity\PageRepository
    indexes:
        mesd_helpwiki_page_parent_id_idx:
            columns: [parent_id]
        mesd_helpwiki_page_user_id_idx:
            columns: [user_id]
    id:
        id:
            id:   true
            type: integer
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   mesd_helpwiki_page_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        title:
            column:   title
            type:     string
            length:   255
            nullable: false
        body:
            column:   body
            type:     text
            nullable: true
            unique:   false
        slug:
            column:   slug
            type:     string
            length:   255
            nullable: false
        revision:
            column:   revision
            type:     integer
            nullable: false
            unique:   false
        printOrder:
            column:   print_order
            type:     integer
            nullable: true
            unique:   false
        dateTime:
            column:   date_time
            type:     datetime
            nullable: false
            unique:   false
        pageLocked:
            column:   page_locked
            type:     boolean
            nullable: true
            unique:   false
        standAlone:
            column:   stand_alone
            type:     boolean
            nullable: true
            unique:   false
        commentsLocked:
            column:   comments_locked
            type:     boolean
            nullable: false
            unique:   false
        editInProgress:
            column:   edit_in_progress
            type:     boolean
            nullable: true  
            unique:   false
        status:
            column:   status
            type:     string
            length:   16
            nullable: false
            unique:   false
            options:
                comment: 'Available types: DRAFT, UNPUBLISHED, PUBLISHED'
    uniqueConstraints:
        mesd_helpwiki_page_title_unique_idx:
            columns: [title]
        mesd_helpwiki_page_slug_unique_idx:
            columns: [slug]
    oneToMany:
        children:
            targetEntity: Mesd\HelpWikiBundle\Entity\Page
            mappedBy:     parent
        comments:
            targetEntity: Mesd\HelpWikiBundle\Entity\Comment
            mappedBy:     page
        permissions:
            targetEntity: Mesd\HelpWikiBundle\Entity\PagePermission
            mappedBy:     page
        histories:
            targetEntity: Mesd\HelpWikiBundle\Entity\History
            mappedBy:     page
        links:
            targetEntity: Mesd\HelpWikiBundle\Entity\Link
            mappedBy:     page
    manyToOne:
        user:
            targetEntity: Mesd\HelpWikiBundle\Model\UserSubjectInterface
            joinColumn:
                name:                 user_id
                referencedColumnName: id
        parent:
            targetEntity: Mesd\HelpWikiBundle\Entity\Page
            inversedBy:   children
            joinColumn:
                name:                 parent_id
                referencedColumnName: id
    manyToMany:
        tags:
            targetEntity: Mesd\HelpWikiBundle\Entity\Tag
            inversedBy:   pages
            joinTable:
                name: mesd_helpwiki_page_tag
                joinColumns:
                    page_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
        media:
            targetEntity: Mesd\HelpWikiBundle\Entity\Media
            inversedBy:   pages
            joinTable:
                name: mesd_helpwiki_page_media
                joinColumns:
                    page_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    media_id:
                        referencedColumnName: id
    lifecycleCallbacks:
