Mesd\HelpWikiBundle\Entity\Page:
    type:            entity
    table:           mesd_helpwiki_page
    repositoryClass: Mesd\HelpWikiBundle\Entity\PageRepository
    indexes:
        mesd_helpwiki_page_parent_id_idx:
            columns: [parent_id]
        mesd_helpwiki_page_user_id_idx:
            columns: [user_id]
    id:
        id:
            type: integer
            id:   true
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   mesd_helpwiki_page_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        title:
            column:   title
            type:     string
            length:   255
            nullable: false
        body:
            column:   body
            type:     text
            nullable: true
            unique:   false
        slug:
            column:   slug
            type:     string
            length:   255
            nullable: false
        revision:
            column:   revision
            type:     integer
            nullable: false
            unique:   false
        printOrder:
            column:   print_order
            type:     integer
            nullable: true
            unique:   false
        dateTime:
            column:   date_time
            type:     datetime
            nullable: false
            unique:   false
        isPageLocked:
            column:   is_page_locked
            type:     boolean
            nullable: false
            unique:   false
        isCommentLocked:
            column:   is_comment_locked
            type:     boolean
            nullable: false
            unique:   false
        isEditInProgress:
            column:   is_edit_in_progress
            type:     boolean
            nullable: true  
            unique:   false
    uniqueConstraints:
        mesd_helpwiki_page_title_unique_idx:
            columns: [title]
        mesd_helpwiki_page_slug_unique_idx:
            columns: [slug]
    oneToMany:
        children:
            targetEntity: Page
            mappedBy:     parent
        comments:
            targetEntity: Comment
            mappedBy:     page
        permissions:
            targetEntity: Permission
            mappedBy:     page
        histories:
            targetEntity: History
            mappedBy:     page
        links:
            targetEntity: Link
            mappedBy:     page
    manyToOne:
        user:
            targetEntity: Mesd\HelpWikiBundle\Model\UserSubjectInterface
            joinColumn:
                name:                 user_id
                referencedColumnName: id
        parent:
            targetEntity: Page
            inversedBy:   children
            joinColumn:
                name:                 parent_id
                referencedColumnName: id
    lifecycleCallbacks: