Mesd\HelpWikiBundle\Entity\PermissionType:
    type:            entity
    table:           mesd_helpwiki_permission_type
    repositoryClass: Mesd\HelpWikiBundle\Entity\PermissionTypeRepository
    id:
        id:
            type: integer
            id:   true
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   mesd_helpwiki_permission_type_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        shortName:
            column:   short_name
            type:     string
            length:   32
            nullable: false
        longName:
            column:   long_name
            type:     string
            length:   64
            nullable: false
            unique:   false
        description:
            column:   description
            type:     text
            nullable: false
            unique:   false
    uniqueConstraints:
        mesd_helpwiki_permission_type_short_name_unique_idx:
            columns: [short_name]