Mesd\HelpWikiBundle\Entity\Permission:
    type:            entity
    table:           mesd_helpwiki_permission
    repositoryClass: Mesd\HelpWikiBundle\Entity\PermissionRepository
    indexes:
        mesd_helpwiki_permission_role_id_idx:
            columns: [role_id]
    id:
        id:
            id:   true
            type: integer
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   mesd_helpwiki_permission_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        object:
            column:   object
            type:     string
            length:   16
            nullable: false
            unique:   false
        type:
            column:   type
            type:     string
            length:   8
            nullable: false
            unique:   false
    uniqueConstraints:
        mesd_helpwiki_permission_object_role_type_unique_idx:
            columns: [object, type, role_id]
    manyToOne:
        role:
            targetEntity: Mesd\HelpWikiBundle\Model\RoleSubjectInterface
            joinColumn:
                name:                 role_id
                referencedColumnName: id