parameters:
    mesd_help_wiki.page_listener.class:      Mesd\HelpWikiBundle\Listener\PageListener
    mesd_help_wiki.comment_listener.class:   Mesd\HelpWikiBundle\Listener\CommentListener
    mesd_help_wiki.listener.heartbeat_listener.class: Mesd\HelpWikiBundle\Listener\HeartbeatListener

services:
    mesd_help_wiki.page_listener:
        class:     %mesd_help_wiki.page_listener.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener,   event: kernel.controller, method: onKernelController, priority: 64 }
            - { name: doctrine.event_listener, event: prePersist  }
            - { name: doctrine.event_listener, event: preUpdate   }
            - { name: doctrine.event_listener, event: postUpdate  }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preRemove   }
    mesd_help_wiki.comment_listener:
        class:     %mesd_help_wiki.comment_listener.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: prePersist  }
            - { name: doctrine.event_listener, event: preUpdate   }
    mesd_help_wiki.listener.heartbeat_listener:
        class:     %mesd_help_wiki.listener.heartbeat_listener.class%
        tags:
            - { name: kernel.event_listener, event: mesd_help_wiki.heartbeat_received, method: populateData }
