parameters:
    mesd_help_wiki.page_listener.class:    Mesd\HelpWikiBundle\Listener\PageListener
    mesd_help_wiki.comment_listener.class: Mesd\HelpWikiBundle\Listener\CommentListener

services:
    mesd_help_wiki.page_listener:
        class:     %mesd_help_wiki.page_listener.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener,   event: kernel.controller, method: onKernelController, priority: 64 }
            - { name: doctrine.event_listener, event: prePersist  }
            - { name: doctrine.event_listener, event: preUpdate   }
            - { name: doctrine.event_listener, event: postUpdate  }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preRemove   }
    mesd_help_wiki.comment_listener:
        class:     %mesd_help_wiki.comment_listener.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: prePersist  }
            - { name: doctrine.event_listener, event: preUpdate   }
