<?php
// src/MESD/HelpWikiBundle/Entity/CommentRepository

namespace MESD\HelpWikiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
}
