<?php
// src/MESD/HelpWikiBundle/Entity/LinkRepository

namespace MESD\HelpWikiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository
{
}
