<?php
// src/MESD/HelpWikiBundle/Entity/PermissionTypeRepository

namespace MESD\HelpWikiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PermissionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionTypeRepository extends EntityRepository
{
}
