<?php
// src/MESD/HelpWikiBundle/Entity/PermissionRepository

namespace MESD\HelpWikiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionRepository extends EntityRepository
{
}
