comment:
    pattern:  /
    defaults: { _controller: "MesdHelpWikiBundle:Comment:index" }

comment_show:
    pattern:  /{id}/show
    defaults: { _controller: "MesdHelpWikiBundle:Comment:show" }

comment_new:
    pattern:  /new
    defaults: { _controller: "MesdHelpWikiBundle:Comment:new" }

comment_create:
    pattern:  /{pageId}/create
    defaults: { _controller: "MesdHelpWikiBundle:Comment:create" }
    requirements: { _method: post }

comment_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MesdHelpWikiBundle:Comment:edit" }

comment_update:
    pattern:  /{id}/update
    defaults: { _controller: "MesdHelpWikiBundle:Comment:update" }
    requirements: { _method: post|put }

comment_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MesdHelpWikiBundle:Comment:delete" }
    requirements: { _method: post|delete }
