MesdHelpWikiBundle_comment_list:
    pattern:  /
    defaults: { _controller: "MesdHelpWikiBundle:Comment:list" }

MesdHelpWikiBundle_comment_view:
    pattern:  /{id}/view
    defaults: { _controller: "MesdHelpWikiBundle:Comment:view" }

MesdHelpWikiBundle_comment_new:
    pattern:  /new
    defaults: { _controller: "MesdHelpWikiBundle:Comment:new" }

MesdHelpWikiBundle_comment_create:
    pattern:  /{pageId}/create
    defaults: { _controller: "MesdHelpWikiBundle:Comment:create" }
    requirements: { _method: post }

MesdHelpWikiBundle_comment_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MesdHelpWikiBundle:Comment:edit" }

MesdHelpWikiBundle_comment_update:
    pattern:  /{id}/update
    defaults: { _controller: "MesdHelpWikiBundle:Comment:update" }
    requirements: { _method: post|put }

MesdHelpWikiBundle_comment_flag:
    pattern:  /{id}/flag
    defaults: { _controller: "MesdHelpWikiBundle:Comment:flag" }
    requirements: { _method: post|put }

MesdHelpWikiBundle_comment_approve:
    pattern:  /{id}/approve
    defaults: { _controller: "MesdHelpWikiBundle:Comment:approve" }
    requirements: { _method: post|put }

MesdHelpWikiBundle_comment_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MesdHelpWikiBundle:Comment:delete" }
    requirements: { _method: post|delete }
