MesdHelpWikiBundle_history_list:
    pattern:  /
    defaults: { _controller: "MesdHelpWikiBundle:History:list" }

MesdHelpWikiBundle_history_view:
    pattern:  /{id}/view
    defaults: { _controller: "MesdHelpWikiBundle:History:view" }

MesdHelpWikiBundle_history_page:
    pattern:  /{id}/page
    defaults: { _controller: "MesdHelpWikiBundle:History:page" }

MesdHelpWikiBundle_history_user:
    pattern:  /{id}/user
    defaults: { _controller: "MesdHelpWikiBundle:History:user" }

MesdHelpWikiBundle_history_new:
    pattern:  /new
    defaults: { _controller: "MesdHelpWikiBundle:History:new" }

MesdHelpWikiBundle_history_create:
    pattern:  /create
    defaults: { _controller: "MesdHelpWikiBundle:History:create" }
    requirements: { _method: post }

MesdHelpWikiBundle_history_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MesdHelpWikiBundle:History:edit" }

MesdHelpWikiBundle_history_update:
    pattern:  /{id}/update
    defaults: { _controller: "MesdHelpWikiBundle:History:update" }
    requirements: { _method: post|put }

MesdHelpWikiBundle_history_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MesdHelpWikiBundle:History:delete" }
    requirements: { _method: post|delete }
