MesdHelpWikiBundle_link_list:
    pattern:  /
    defaults: { _controller: "MesdHelpWikiBundle:Link:list" }

MesdHelpWikiBundle_link_view:
    pattern:  /{id}/view
    defaults: { _controller: "MesdHelpWikiBundle:Link:view" }

MesdHelpWikiBundle_link_new_by_route:
    pattern:  /new/{route}/new
    defaults: { _controller: "MesdHelpWikiBundle:Link:newByRoute" }

MesdHelpWikiBundle_link_new_by_page:
    pattern:  /page/new
    defaults: { _controller: "MesdHelpWikiBundle:Link:createNewLinkPage" }

MesdHelpWikiBundle_link_new:
    pattern:  /new
    defaults: { _controller: "MesdHelpWikiBundle:Link:new" }

MesdHelpWikiBundle_link_create:
    pattern:  /create
    defaults: { _controller: "MesdHelpWikiBundle:Link:create" }
    requirements: { _method: post }

MesdHelpWikiBundle_link_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MesdHelpWikiBundle:Link:edit" }

MesdHelpWikiBundle_link_update:
    pattern:  /{id}/update
    defaults: { _controller: "MesdHelpWikiBundle:Link:update" }
    requirements: { _method: post|put }

MesdHelpWikiBundle_link_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MesdHelpWikiBundle:Link:delete" }
    requirements: { _method: post|delete }
