MesdHelpWikiBundle_media_list:
    pattern:  /
    defaults: { _controller: "MesdHelpWikiBundle:Media:list" }

MesdHelpWikiBundle_media_view:
    pattern:  /{id}/view
    defaults: { _controller: "MesdHelpWikiBundle:Media:view" }

MesdHelpWikiBundle_media_new:
    pattern:  /new
    defaults: { _controller: "MesdHelpWikiBundle:Media:new" }

MesdHelpWikiBundle_media_create:
    pattern:  /create
    defaults: { _controller: "MesdHelpWikiBundle:Media:create" }
    requirements: { _method: post }

MesdHelpWikiBundle_media_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MesdHelpWikiBundle:Media:edit" }

MesdHelpWikiBundle_media_update:
    pattern:  /{id}/update
    defaults: { _controller: "MesdHelpWikiBundle:Media:update" }
    requirements: { _method: post|put }

MesdHelpWikiBundle_media_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MesdHelpWikiBundle:Media:delete" }
    requirements: { _method: post|delete }

MesdHelpWikiBundle_media_upload:
    pattern: /upload
    defaults: { _controller: "MesdHelpWikiBundle:Media:upload" }
    requirements: { _method: get|post|put }