MesdHelpWikiBundle_pagepermission_index:
    pattern:  /
    defaults: { _controller: "MesdHelpWikiBundle:PagePermission:index" }

MesdHelpWikiBundle_pagepermission_show:
    pattern:  /{id}/show
    defaults: { _controller: "MesdHelpWikiBundle:PagePermission:show" }

MesdHelpWikiBundle_pagepermission_new:
    pattern:  /new
    defaults: { _controller: "MesdHelpWikiBundle:PagePermission:new" }

MesdHelpWikiBundle_pagepermission_create:
    pattern:  /create
    defaults: { _controller: "MesdHelpWikiBundle:PagePermission:create" }
    requirements: { _method: post }

MesdHelpWikiBundle_pagepermission_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MesdHelpWikiBundle:PagePermission:edit" }

MesdHelpWikiBundle_pagepermission_update:
    pattern:  /{id}/update
    defaults: { _controller: "MesdHelpWikiBundle:PagePermission:update" }
    requirements: { _method: post|put }

MesdHelpWikiBundle_pagepermission_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MesdHelpWikiBundle:PagePermission:delete" }
    requirements: { _method: post|delete }
