# @todo this is only here until breadcrumbs are fixed
# this path prevents users from going to a 403 page
MesdHelpWikiBundle_page_list:
    pattern:      /
    defaults:     { _controller: "MesdHelpWikiBundle:Page:toc" }

MesdHelpWikiBundle_page_new:
    pattern:      /new
    defaults:     { _controller: "MesdHelpWikiBundle:Page:new" }

MesdHelpWikiBundle_page_create:
    pattern:      /create
    defaults:     { _controller: "MesdHelpWikiBundle:Page:create" }
    requirements: { _method: post }

MesdHelpWikiBundle_page_view:
    pattern:      /{slug}/view
    defaults:     { _controller: "MesdHelpWikiBundle:Page:view" }

MesdHelpWikiBundle_page_edit:
    pattern:      /{id}/edit
    defaults:     { _controller: "MesdHelpWikiBundle:Page:edit" }
    requirements:
        id:  \d+

MesdHelpWikiBundle_page_update:
    pattern:      /{id}/update
    defaults:     { _controller: "MesdHelpWikiBundle:Page:update" }
    requirements:
        id:  \d+
        _method: post|put

MesdHelpWikiBundle_page_delete:
    pattern:      /{id}/delete
    defaults:     { _controller: "MesdHelpWikiBundle:Page:delete" }
    requirements:
        id:  \d+
        _method: post|delete

MesdHelpWikiBundle_page_order_edit:
    pattern:      /order/edit
    defaults:     { _controller: "MesdHelpWikiBundle:Page:editOrder" }

MesdHelpWikiBundle_page_order_update:
    pattern:      /order/update
    defaults:     { _controller: "MesdHelpWikiBundle:Page:updateOrder" }
    requirements: { _method: post|put }

MesdHelpWikiBundle_page_comments_view:
    pattern:      /{id}/comments/view
    defaults:     { _controller: "MesdHelpWikiBundle:Page:commentsView" }