MesdHelpWikiBundle_permission_list:
    pattern:  /
    defaults: { _controller: "MesdHelpWikiBundle:Permission:list" }

MesdHelpWikiBundle_permission_view:
    pattern:  /{id}/view
    defaults: { _controller: "MesdHelpWikiBundle:Permission:view" }

MesdHelpWikiBundle_permission_new:
    pattern:  /new
    defaults: { _controller: "MesdHelpWikiBundle:Permission:new" }

MesdHelpWikiBundle_permission_create:
    pattern:  /create
    defaults: { _controller: "MesdHelpWikiBundle:Permission:create" }
    requirements: { _method: post }

MesdHelpWikiBundle_permission_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MesdHelpWikiBundle:Permission:edit" }

MesdHelpWikiBundle_permission_update:
    pattern:  /{id}/update
    defaults: { _controller: "MesdHelpWikiBundle:Permission:update" }
    requirements: { _method: post|put }

MesdHelpWikiBundle_permission_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MesdHelpWikiBundle:Permission:delete" }
    requirements: { _method: post|delete }

MesdHelpWikiBundle_permission_page_view:
    pattern:  /page/{id}/view
    defaults: { _controller: "MesdHelpWikiBundle:Permission:pageView" }

MesdHelpWikiBundle_permission_page_new:
    pattern:  /page/{id}/new
    defaults: { _controller: "MesdHelpWikiBundle:Permission:pageNew" }

MesdHelpWikiBundle_permission_page_create:
    pattern:  /page/{id}/create
    defaults: { _controller: "MesdHelpWikiBundle:Permission:pageCreate" }
    requirements: { _method: post }

MesdHelpWikiBundle_permission_page_edit:
    pattern:  /page/{id}/edit
    defaults: { _controller: "MesdHelpWikiBundle:Permission:pageEdit" }

MesdHelpWikiBundle_permission_page_update:
    pattern:  /page/{id}/update
    defaults: { _controller: "MesdHelpWikiBundle:Permission:pageUpdate" }
    requirements: { _method: post|put }

MesdHelpWikiBundle_permission_page_delete:
    pattern:  /page/{id}/delete
    defaults: { _controller: "MesdHelpWikiBundle:Permission:pageDelete" }
    requirements: { _method: post|delete }
